m = float(input('Type a distance in metres: '))
print('{}m is the same as: '.format(m))
print('{}km'.format(m / 1000))
print('{}hm'.format(m / 100))
print('{}dam'.format(m / 10))
print('{}dm'.format(m * 10))
print('{}cm'.format(m * 100))
print('{}mm'.format(m * 1000))
